language: node_js
node_js:
  - "node"
branches:
  only:
  - master
  - develop
before_script:
  - sudo apt-get update
  - sudo apt-get install python3
  - npm install
  - echo $PWD
  - ls
  - ls ../.
compiler:
  - gcc
  - clang
install:
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang